<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Eco.ReferenceAssemblies" />
	  <PackageReference Include="ConcurrentHashSet" />
	  <PackageReference Include="Newtonsoft.Json" />
	  <PackageReference Include="StrangeLoopGames.PropertyChanged.Fody" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ConcurrentCollections">
      <HintPath>..\ConcurrentCollections.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
