<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Eco.ReferenceAssemblies" />
	  <PackageReference Include="ConcurrentHashSet" Version="1.3.0" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="StrangeLoopGames.PropertyChanged.Fody" Version="3.4.2-slg.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ConcurrentCollections">
      <HintPath>..\ConcurrentCollections.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
