# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build, test, sign and package a WPF or Windows Forms desktop application
# built on .NET Core.
# To learn how to migrate your existing application to .NET Core,
# refer to https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework
#
# To configure this workflow:
#
# 1. Configure environment variables
# GitHub sets default environment variables for every workflow run.
# Replace the variables relative to your project in the "env" section below.
#
# 2. Signing
# Generate a signing certificate in the Windows Application
# Packaging Project or add an existing signing certificate to the project.
# Next, use PowerShell to encode the .pfx file using Base64 encoding
# by running the following Powershell script to generate the output string:
#
# $pfx_cert = Get-Content '.\SigningCertificate.pfx' -Encoding Byte
# [System.Convert]::ToBase64String($pfx_cert) | Out-File 'SigningCertificate_Encoded.txt'
#
# Open the output file, SigningCertificate_Encoded.txt, and copy the
# string inside. Then, add the string to the repo as a GitHub secret
# and name it "Base64_Encoded_Pfx."
# For more information on how to configure your signing certificate for
# this workflow, refer to https://github.com/microsoft/github-actions-for-desktop-apps#signing
#
# Finally, add the signing certificate password to the repo as a secret and name it "Pfx_Key".
# See "Build the Windows Application Packaging project" below to see how the secret is used.
#
# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
# refer to https://github.com/microsoft/github-actions-for-desktop-apps

name: .NET Core Desktop

on:
  push:
    branches:
      - '*'
      - main
      - develop
    tags:
      - '*.*.*'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_FILE: Eco.Systems.Permissions/Eco.Systems.Permissions.csproj
  DOTNET_VERSION: 8.0.x
  TEST_RESULTS_DIR: TestResults
  PUBLISH_DIR: publish
  PACKAGE_VERSION: 1.0.0
  ASSEMBLY_VERSION: 1.0.0
  FILE_VERSION: 1.0.0
  # Replace with your solution name, i.e. MyWpfApp.sln.
  Solution_Name: Eco.Systems.Permissions.Sln
  # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
  Test_Project_Path: your-test-project-path
  # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
  Wap_Project_Directory: your-wap-project-directory-name
  # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.
  Wap_Project_Path: your-wap-project-path

jobs:

  build:

    strategy:
      matrix:
        configuration:
          - Debug
          - Release
        eco_version:
          # - Eco-0.11
          - Eco-0.13

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        cache: true

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    # - name: Setup MSBuild.exe
    #   uses: microsoft/setup-msbuild@v3

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: |
        dotnet test ${{ env.PROJECT_FILE }}`
          --configuration ${{ matrix.configuration }} `
          --no-build `
          --logger "trx" `
          --results-directory ${{ env.TEST_RESULTS_DIR }} `
          --property:EcoVersion=${{ matrix.eco_version }}

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      # run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      run: |
        dotnet restore ${{ env.PROJECT_FILE }}`
          --property:EcoVersion=${{ matrix.eco_version }}
      # env:
      #   Configuration: ${{ matrix.configuration }}

    # Build the dll file
    - name: Build the application
      # run: msbuild $env:Solution_Name /t:Build /p:Configuration=$env:Configuration
      run: |
        dotnet build ${{ env.PROJECT_FILE }}`
          --configuration ${{ matrix.configuration }} `
          --no-restore `
          --property:Version=${{ env.PACKAGE_VERSION }} `
          --property:AssemblyVersion=${{ env.ASSEMBLY_VERSION }} `
          --property:FileVersion=${{ env.FILE_VERSION }} `
          --property:InformationalVersion="${GITHUB_SHA::7}" `
          --property:EcoVersion=${{ matrix.eco_version }}
      # env:
      #   Configuration: ${{ matrix.configuration }}

    - name: Publish
      run: dotnet publish -c ${{ matrix.configuration }} -o ${{ env.PUBLISH_DIR }}

    - uses: actions/upload-artifact@v7
      with:
        name: Eco.Systems.Permissions
        path: ${{ env.PUBLISH_DIR }}

    # Store .dll as artifact
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.configuration }}-Eco.Systems.Permissions.dll
        path: ./Eco.Systems.Permissions/obj/${{ matrix.configuration }}/net8.0/Eco.Systems.Permissions.dll
        retention-days: 5

    - uses: actions/upload-artifact@v7
      if: always()
      with:
        name: test-results
        path: ${{ env.TEST_RESULTS_DIR }}
